// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thsthmaujmktlwvkpsxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoc3RobWF1am1rdGx3dmtwc3hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjI4ODMsImV4cCI6MjA1Nzc5ODg4M30.8xS8Km6gLEG40CXjPXgAgVS19bqo92OEf2qApS0JBew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);